import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({subsets: ['latin']})

function SectionPersonalInfo() {
  return (
    <fieldset>
      <label htmlFor="">Enter Your First Name:</label>
      <label htmlFor="">Enter Your Last Name:</label>
      <label htmlFor="">Enter Your Email:</label>
      <label htmlFor="">Create A New Password:</label>
    </fieldset>
  )
}

function SectionAccountType() {
  return (
    <fieldset>
    </fieldset>
  )
}

function SectionProfile() {
  return (
    <fieldset>
    </fieldset>
  )
}

function Body() {
  return (
    <main>
      <h1 style={{'text-align': 'center', margin: 'auto auto', padding: 'auto auto'}}>User Form</h1>
      <p>Please fill out this form with the required information.</p>
      
      {/* the form body */}
      <form method='POST' action=''>
        <SectionPersonalInfo />
        <SectionAccountType />
      </form>
      <SectionProfile />
    </main>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body class='Body' />
    </>
  )
}
